### ISSUE TITLE
"browser" field inconsistency

### ISSUE THREAD

**Issue by feross** [substack/node-browserify#1088] opened 2015-01-24 02:18 UTC
In `package.json`, to **exclude** a file `./lib/foo.js` that is required with `require('./lib/foo')` (note the missing `.js` extension) you must do:

```json
"browser": {
  "./lib/foo": false
}
```

This won't work:

```json
"browser": {
  "./lib/foo.js": false
}
```

It's weird because you must do the opposite (include the `.js`) to substitute a file. Say you want to **substitute** a file that is required with `require('./lib/foo')` (note the missing `.js` extension), you must do:

```json
"browser": {
  "./lib/foo.js": "./lib/browser.js"
}
```

This won't work:

```json
"browser": {
  "./lib/foo": "./lib/browser"
}
```

Browserify 8.1.1.

**Comment by jmm** [comment] 2015-01-28 16:50
Currently there's widespread flakiness in browserify about interpreting input as module IDs vs paths and resolving paths consistently. This issue is an example of that (although it's actually node-browser-resolve where the important stuff is happening). The cause is [this part](https://github.com/defunctzombie/node-browser-resolve/blob/764fb982caf56c828da57a0c2b743d7eb0765053/index.js#L57-L77) in node-browser-resolve's `find_shims_in_package()`:

```js
    Object.keys(info.browser).forEach(function(key) {
        if (info.browser[key] === false) {
            return shims[key] = __dirname + '/empty.js';
        }

        // elided

        key = path.resolve(cur_path, key);
        shims[key] = val;
    });
```

You can see that if the value is `false` the `key` is stored in `shims` unchcanged, but otherwise the `key` is later pseudo-resolved to a path using `path.resolve()` and stored in `shims`. 

Later the fully resolved path from the `require()` is used as a key to `shims`. So if you put `./lib/foo` as a key in `browser` it will be pseudo-resolved to something like `shims['/basedir/lib/foo']`. The `require('./lib/foo')` will be actually resolved and then node-browser-resolve will try to access `shims['/basedir/lib/foo.js']`.

The values in `browser` are *also* pseudo resolved, so this...

```js
"browser": {
  "./lib/foo.js": "./lib/browser"
}
```

...generates an `Error: ENOENT`.

Directory structure also affects how these values match up. I assume that in your test case `lib/` and the `require()`ing file are in the same directory as `package.json`, but things get more complicated if they're not.

**Comment by monsanto** [comment] 2015-02-25 08:14
Ran into this weirdness with `false` today. +1 to making the browser field more consistent. I feel like it never works the way I expect it to...

**Comment by substack** [comment] 2015-12-06 01:04
These issues have been fixed upstream in browser-resolve: https://github.com/defunctzombie/node-browser-resolve/pull/75

and I've added a litany of test cases to the test suite in test/browser_field_resolve/{g,h,i,j} and the others.

**Closed by substack** 2015-12-06 01:04 UTC
