### ISSUE TITLE
Getting an "Object is not a constructor error" why trying to browserify an npm module I wrote

### ISSUE THREAD

**Issue by SamHausmann** [substack/node-browserify#1554] opened 2016-05-04 20:10 UTC
I'm the author of the `rosette-api` npm module which can be found at https://www.npmjs.com/package/rosette-api.

I'm working on a chrome extension that leverages this npm module and I'm trying to use browserify.

When I load the module, I'm getting the error `Api is not a constructor`.

I have all my code in a file called `test.js` and have a `bundle.js` file which is included in my html.

Here is the code for `test.js`

```javascript
var Api = require("rosette-api");

var api = new Api('api_key');
var endpoint = "ping";

api.rosette(endpoint, function(err, res){
	if(err){
		console.log(err)
	} else {
		console.log(JSON.stringify(res, null, 2));
	}
});
```

I'm running npm run build every time I test my extension and have my build script in `package.json`
I already tried the demo with `uniq` and it worked fine so could it be something with my npm module? I also tried including it locally to no avail.

Any idea why I might be getting this message? I'm at a loss. Thanks!

**Comment by jmm** [comment] 2016-05-05 13:05
Hello @SamHausmann. Your package is kind of confusing -- it doesn't appear to export anything as the "default" export (e.g. it seems you'd need to do `require("rosette-api").Api` to accomplish what you want), and the usage example shows invalid code:

```js
var rosette-api = require('rosette-api');

var api = new Api(API_KEY);
```

Since I suspect this isn't a problem in Browserify, I'm closing this issue. If there is a Browserify problem, please open a new issue with a minimal reproduction. If you need help getting started check out https://github.com/miniminirepro/browserify/tree/api.

Thanks!

**Closed by jmm** 2016-05-05 13:05 UTC

**Comment by SamHausmann** [comment] 2016-05-05 14:11
Thanks for your help. I wasn't aware of this invalid behavior because our unit tests were only testing our local code, not what's on npm. Everything seems to be working fine now.
