### ISSUE TITLE
Modules are executed multiple times when using symlinks in node_modules

### ISSUE THREAD

**Issue by epeli** [substack/node-browserify#1063] opened 2015-01-09 14:34 UTC
I have following symlink in my project

    ln -sf .. node_modules/app

and I require modules like this

```js
var config = require("app/config");
```
etc.

but in this case the config module is executed multiple times when it is required from different js files.

Here's smallest possible example reproducing this https://github.com/epeli/browserify-bug

This bug was introduced in the 8.0.0 release.

--

The symlink idea is from the browserify handbook https://github.com/substack/browserify-handbook#symlink

**Comment by epeli** [comment] 2015-01-09 14:46
This commit breaks the example code https://github.com/substack/node-browserify/commit/324991581baf2797794207efc42ab18957635182

**Comment by epeli** [comment] 2015-01-09 14:49
Also after inspecting the generated bundle the config.js is not duplicated in the bundle. It's just executed twice.

**Comment by ashaffer** [comment] 2015-01-09 21:00
+1

**Comment by feross** [comment] 2015-01-11 22:20
@epeli Thanks for proving an example. I confirmed that this is indeed a bug in browserify.

**Comment by spudly** [comment] 2015-02-09 19:49
Same problem here, but I'm not using symlinks. I have four modules that all require the same version of the same package. That package is included once, but executed 4 times.

**Comment by timoxley** [comment] 2015-02-23 06:27
have experimented at length with various solutions to this and not easy to have browserify only pay attention to realpaths as it seems to require realpath awareness across multiple modules and pipeline steps. 

Likely I just have NFI what I'm doing though, would appreciate @substack perhaps pointing in the right direction how to make browserify/watchify symlink aware.

**Comment by jamieowen** [comment] 2015-05-11 15:44
+1

**Comment by chrisirhc** [comment] 2015-06-29 23:14
After doing a lot of digging, I found that this behavior is intentional and by design according to https://github.com/substack/node-browserify/issues/1027 and https://github.com/substack/node-browserify/commit/4c04362572567511747df8322c9ff2ca855f2825.
It seems that the module will always be re-initialized even if they're identical.

I think people working with common libraries (e.g. three.js and react) might want an aggressive version of dedupe that actually reuses the same instance. Perhaps this feature can be opt-in, such as an option called `dedupeInstance`?

**Comment by dogada** [comment] 2015-06-30 12:14
I don't think this behavior is intentional. Ticket #1027 resolves issue with importing of *different* modules with *same* content. But in our case we import *same* module in different places, so we should receive same module instance everywhere as it works in Node.

I resolved this issue for myself by moving dependency that MUST be singleton to the own standalone module that I access via global variable in rest of NPM-modules of my application. Not too nice but works.

**Comment by rikukissa** [comment] 2015-06-30 12:33
We've been struggling with this problem also. One temporary "solution" we found was to use [browserify-resolutions](https://github.com/Updater/browserify-resolutions) which seems to handle this problem in most cases. I would still like to see an example of how this should be done "the right way" while developing submodules for a project.

**Comment by chrisirhc** [comment] 2015-06-30 21:14
There are two ways to differentiate the modules to be imported:
* string argument you provide to `require()`  
For example: `require('a')` vs `require('b')` or `require('./a')` vs `require('../a')`
* The source contents of the module code

I think the crux of this problem is that browserify isn't aware of the real path of the module.
Perhaps browserify should call realPath on the path returned from the resolves to determine if they're the same file?

**Comment by chrisirhc** [comment] 2015-06-30 21:39
I've made a PR (#1318) for getting the real path and resolving the packages via their real paths.

**Closed** 2015-07-09 23:07 UTC
