### ISSUE TITLE
Browserify 8.1.1 break require option when transform CoffeeScript

### ISSUE THREAD

**Issue by daiweilu** [substack/node-browserify#1074] opened 2015-01-16 19:43 UTC
In short, if you use `coffeeify` transform and `require` option together, you have module not found error for required modules. The `extensions` option doesn't help browserify to find `.coffee` files. 

One solution is that you have to specify `.coffee` when you `bundle.require()` something, which makes external requires works like `require('./file.coffee')`, where we supposed to write `require('./file')`.

Example: https://github.com/daiweilu/browserify-coffeeify-broken-require

Run `gulp bundle:coffee`, open `./dist/index.html`, and see everything has to be appended with `.coffee`.

**Comment by jmm** [comment] 2015-01-16 20:49
So is the `dist/desktop-coffee.bundle.js` in your repo what browserify produced, or did you edit it?

**Comment by jmm** [comment] 2015-01-16 20:50
And can't the example be simplified a lot?

**Comment by daiweilu** [comment] 2015-01-16 20:57
@jmm Yes `dist/desktop-coffee.bundle.js` is what produced. And now I removed everything that's not needed.

**Comment by jmm** [comment] 2015-01-16 22:11
@daiweilu Great, thanks. However, you should get rid of all the gulp stuff and just isolate it to the browserify stuff.

@substack I haven't traced this all the way through yet, but I believe this is because previously module-deps would have resolved the pathname for the `.require()`'d file, with access to `opts.extensions`. But as a result of the changes you made in response to #1059 they are now resolved in `b.require()` without access to the extensions. I will try to confirm. If so this will dovetail with the pull request I was going to send anyway to do pathname resolution in module-deps.

**Comment by jmm** [comment] 2015-01-16 23:02
With the changes I've been readying for a pull request as a followup to #1059, @daiweilu's code works with '.coffee' removed from everywhere `src-coffee/client/common/boop.coffee` is required (e.g. removed in `gulpfile.js` and `dist/index.html`). While debugging this I did find a problem with my changes that wasn't caught by existing tests, so that's good.

**Comment by daiweilu** [comment] 2015-01-20 22:34
Just want to follow up on the process.

**Comment by jmm** [comment] 2015-01-20 22:40
@daiweilu I don't speak for the project, but I believe #1077 will (eventually) fix the problem and should be adopted for other reasons as well.

**Comment by jmm** [comment] 2015-03-17 14:56
@daiweilu I see that your example repo is gone. If this is still a problem in browserify v9.0.3 or later please open a new issue with a minimal reproduction.

**Closed by jmm** 2015-03-17 14:56 UTC
