### ISSUE TITLE
Should prfioritize `window` over `global` when inserting global vars

### ISSUE THREAD

**Issue by jahtalab** [substack/node-browserify#1558] opened 2016-05-11 12:45 UTC
Browserify generates this code when it detects the use of global object:

```javascript

(function(global){
/// the rest
}).call(this, typeof global !== "undefined" ? global : typeof self !== "undefined" ? self : typeof window !== "undefined" ? window : {})
```

shouldn't it first check for `window` if it's not available then use `self` and then `global`?

**Comment by jmm** [comment] 2016-05-11 12:53
Hi, @jahtalab, thanks for the report. This seems to be a duplicate of https://github.com/substack/node-browserify/issues/1189, so I'll close in favor of that. See also https://github.com/substack/insert-module-globals/pull/48.

**Closed by jmm** 2016-05-11 12:53 UTC
