### ISSUE TITLE
browserify applies transforms to npm linked modules

### ISSUE THREAD

**Issue by jayphelps** [substack/node-browserify#1386] opened 2015-09-21 18:56 UTC
If you `npm link` a module into your browserify project, it incorrectly has transforms applied to it. This becomes a major issue particularly if the module you install relies on non-strict mode and you're using babelify, which inserts `"use strict"`, causing it to error.

Here's a repo to reproduce: https://github.com/jayphelps/browserify-bug. The major step to note in the README is that you must git clone the external module and `npm link` it for the bug to show.

Also note that very new versions of babel proactively transform certain strict mode code, like `this.foo` to `undefined.foo`. Don't let this confuse you.

**Comment by jmm** [comment] 2015-09-21 19:49
Hmm, I wonder if this could be from #1318.

**Comment by jayphelps** [comment] 2015-09-21 20:07
Cc/ @chrisirhc

**Comment by jmm** [comment] 2015-09-23 17:06
Maybe related: #1365.

**Comment by chrisirhc** [comment] 2015-09-23 18:01
Definitely sounds like it's related to #1365. If nobody else gets to this, I'll look into it later today.

**Comment by ivantsepp** [comment] 2015-09-23 20:37
Ah thanks for linking me to this issue @jmm!

This matches the behavior I'm seeing. The babel transform is being applied to a symlinked node_module when it shouldn't be.

**Comment by chrisirhc** [comment] 2015-09-24 20:42
I've come up with a quick hackish solution to resolve this (https://github.com/substack/module-deps/pull/99, #1392). It's up for comment and review.

**Comment by polkovnikov-ph** [comment] 2015-10-01 19:13
Is there any workarounds for this issue except hand-patching `node_modules`? Build of my project fails because of this.

**Comment by jayphelps** [comment] 2015-10-01 20:28
switch to webpack :trollface: that's what I did.

**Comment by polkovnikov-ph** [comment] 2015-10-01 20:52
I've though about it for a long time :trollface:

**Comment by jmm** [comment] 2015-10-01 21:16
Off with your heads!

@polkovnikov-ph I'm still working from the assumption that this is a result of #1318. Could you downgrade to `browserify@<10.2.5` for now if that resolves it? As you wrote in the other issue, Babel's `ignore` option is another possibility, but that could get messy.

**Comment by chrisirhc** [comment] 2015-10-02 00:13
@jmm, it *is* caused by #1318. I've submitted a fix for this as I mentioned above.

**Comment by jmm** [comment] 2015-10-02 02:01
@chrisirhc Ok, thanks for confirming and for the PR. I haven't had a real good look at either #1318 or the new PR and I hadn't seen you say whether or not it had resulted from #1318, so I wasn't sure.

**Comment by substack** [comment] 2015-10-28 09:55
This is fixed in 12.0.1.

**Closed by substack** 2015-10-28 09:55 UTC
Labels: path-matching

**Comment by kintel** [comment] 2015-11-19 05:35
@substack See #1437 - I believe this should be reopened.

**Comment by TehShrike** [comment] 2015-12-06 03:30
I encountered this issue when using browserify 12.0.1.
