### ISSUE TITLE
"Error: path must be a string" (v5.10.0)

### ISSUE THREAD

**Issue by orcaman** [substack/node-browserify#884] opened 2014-09-01 13:01 UTC
Hi,

I have this file (a large bundle of a couple of JS files) that used to work with browserify (5.10.0
) till a couple of days ago, and now it does not. 

This is what I am running:
$ browserify index.js -o dist/out.bundle.js 

And the output is:
Error: path must be a string
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:15:16
    at process._tickCallback (node.js:419:13)

Is there a way I can debug this to try and figure out what bothers browserify? 

Cheers

**Comment by Tzrlk** [comment] 2015-01-13 01:59
I'm running into this issue now in 8.1.0

**Comment by Tzrlk** [comment] 2015-01-13 21:13
I had success exposing the real error message by catching the error during my gulp build:

```javascript
bundler.bundle()
	.on('error', function (error) {
		gutil.log('Browserify Error', error.message);
		this.emit('end');
	})
.pipe(source('client.js'))
...etc
```

Of course, that just seemed to uncover another layer of 'path must be a string'. *sigh*

Digging in, the problem looks like it's with index.js's makeTransform function:

```javascript
function makeTransform (tr, cb) {
    var trOpts = {};
    if (Array.isArray(tr)) {
        trOpts = tr[1];
        tr = tr[0];
    }
    if (typeof tr === 'function') {
        var t = tr(file, trOpts);
        self.emit('transform', t, file);
        nextTick(cb, null, wrapTransform(t));
    }
    else {
        loadTransform(tr, trOpts, function (err, trs) {
            if (err) return cb(err);
            cb(null, wrapTransform(trs));
        });
    }
}
```

The type of `tr` is 'object' (Stream), so it will always fall back to the last condition, which assumes it's a string. A simple fix can stop this from happening (`else if(typeof tr === 'string')`), but it won't deal with the stream properly.

**Comment by Rob-pw** [comment] 2015-01-15 14:38
Any progress on this bug? Encountered this unhelpful error and unsure as to where I'm going wrong in my usage of browserify. 

```javascript
var browserified = transform(function (filename) {
            var b = browserify();

            b.add(filename);

           b.transform('brfs');

           return b.bundle();
       });
```

**Comment by Tzrlk** [comment] 2015-01-15 20:20
Ah yes, in my case it was my use of transform functions. I was including browserify-shim, but adding the transform like so:

```javascript
var shim = require('browserify-shim');

var bundler = browserify(config);
bundler.transform(shim({
    './node_modules/angular/angular.js': 'angular'
}));
```

Which caused a stream to be emitted and stored as the transform. The correct way of implementing that particular transform is to follow the documentation for it, and configure it in the `package.json`.

However, I also found that debugging browserified code is a nightmare, so I switched back to using requirejs.

**Comment by kentor** [comment] 2015-03-19 17:33
Hmm I'm having the same problem with envify

```javascript
browserify(entry)
    .transform(envify({
      NODE_ENV: 'production',
    }))
    .bundle()
```

sadly there isn't a package.json config for envify. so yeah, the error message isn't helpful at all and I don't know what to do

**Comment by kuraga** [comment] 2015-04-27 18:48
Updates?

**Comment by zertosh** [comment] 2015-04-29 00:51
If someone can provide me with a repo I can use to reproduce it, I'd be more than happy to fix it.

**Comment by chrisaspringer** [comment] 2015-09-15 20:50
Maybe try it with Faker?
https://github.com/Marak/faker.js

**Comment by jmm** [comment] 2015-09-15 21:20
I'm closing this because there's not enough information to reproduce. If anyone is still experiencing this problem, please open a new issue that follows the guidelines in [How to report issues with browserify](https://github.com/substack/node-browserify/wiki/How-to-report-issues-with-browserify).

**Closed by jmm** 2015-09-15 21:20 UTC
Labels: repro-please, support

**Comment by fchastanet** [comment] 2015-11-16 22:16
Thank you Tzrlk, 
I have more information on the error graceful to the on('error', ...

**Comment by btipling** [comment] 2016-02-11 22:34
For anyone else running into this, this an error I get when I had a typo:

```javascript
    bundler.transform(envify({
        NODE_ENV: 'production'
    }));
```

Instead of:

```
    bundler.transform(envify, {
        NODE_ENV: 'production'
    });
```

**Comment by kcahir** [comment] 2017-04-15 02:11
The envify example can be fixed by replacing:
```
browserify(entry)
  .transform(envify({
    NODE_ENV: 'production'
  }))
  .bundle()
```
with
```
browserify(entry)
.transform("envify",{
    NODE_ENV: 'development'
})
.bundle()
```
