### ISSUE TITLE
Browserify does not allow the requiring of standard JSON.

### ISSUE THREAD

**Issue by ariporad** [substack/node-browserify#1339] opened 2015-07-26 15:17 UTC
Hi Everyone,

I'm using grunt-browserify (and by extension browserify), and have discovered something rather peculiar:

I have a json file, called common.json. If I try to require it like this (valid JSON):

    {
      "name": "Ari is the King"
    }

It throw an error, Unexpected token at 2:8.

If I make it like this (invalid JSON): 

    {
      name: "Ari is the King"
    }

Everything works well.

I think this is a bug, or is it some kind of intended behavior?

I ***think*** it's caused by browserify prepending module.exports onto the file, and for some reason not allowing quoted keys in JS.

Thanks!

**Comment by jmm** [comment] 2015-07-27 14:19
@ariporad Thanks for your interest in browserify! That is peculiar. I'm sorry, but I can't reproduce this. Because there's not enough information here to reproduce the problem I'm closing the issue, but feel free to open a new issue that follows the guidelines in [How to report issues with browserify](https://github.com/substack/node-browserify/wiki/How-to-report-issues-with-browserify). Please reproduce this without any additional wrapper link grunt / grunt-browserify in the picture. If you can't, then perhaps it's an issue with the wrapper.

Thanks!

**Closed by jmm** 2015-07-27 14:19 UTC
