### ISSUE TITLE
control the order of transforms

### ISSUE THREAD

**Issue by andrepadez** [substack/node-browserify#1285] opened 2015-05-25 02:49 UTC
use case:
```javascript
var aliasify = require('aliasify');
var myTransform = require('my-custom-transform');
...
b.transform(aliasify);
b.transform(myTransform);
```

I expect that files being compiled go through aliasify before running through myTransform.
I tried switching the order of lines 4 and 5, and i get the same result, which is myTransform is being applied first.

Is there a way to control this? if not, would you consider implementing it?
Thanks

**Comment by jmcantrell** [comment] 2015-05-28 20:51
It looks like [this](https://github.com/substack/node-browserify/blob/master/index.js#L299) is supposed to ensure the order of the transforms. Do you have some code that demonstrates this?

**Comment by jmm** [comment] 2015-05-28 20:55
Thanks for commenting @jmcantrell. @andrepadez What browserify version and OS? As @jmcantrell noted, they are supposed to be applied in the order added. Can you please create a repo that reproduces the problem?

**Comment by kentmw** [comment] 2016-04-28 19:15
I am experiencing this issue, I believe, when using hbsfy and aliasify together. I want to reference a partial inside a handlebars template using an alias. Hbsfy will convert my partial references into `require(...)` invocations, which should let aliasify further convert them. However, when I put console.logs in both hbsfy and aliasify they were dumping out logs at the same time, suggesting hbsfy was not complete before aliasify started working.

 This is my configuration:
```
  var browserify = require('browserify');
  var b = browserify();
  b.add('./app/init');
  b.transform('hbsfy', { traverse: true });
  b.transform('aliasify');
```
```
{
  "aliasify": {
    "aliases": {
      "app": "./app"
    }
  }
}
```
and I'm referencing this alias in my templates:
```
  {{> app/myPartial.hbs }}
```
I'm getting this error:
```
Error: Cannot find module 'app/myPartial.hbs' from '/other/dev' 
```
and the logs were interlaced:
```
aliasify - /other/dev/myView.js: replacing app/myFile.js with ./../myFile of function require
var partial$0 = require('app/myPartial.hbs');
aliasify - /other/dev/mySecondView.js: replacing app/mySecondFile.js with ./../mySecondFile of function require
```
Here is the issue on hbsfy: https://github.com/epeli/node-hbsfy/issues/56
I'm using browserify version 13.0.0

**Comment by kentmw** [comment] 2016-04-28 19:37
Perhaps there is some asynchronous aspect to some of these transforms? Perhaps the hbsfy function will end before it has completed updating the files? It doesn't [look](https://github.com/substack/node-browserify/blob/master/index.js#L83-L86) like browserify handles promise resolution for transforms, and it's expected that everything is completed when the transform returns.

**Comment by jmm** [comment] 2016-04-28 21:35
Hi @kentmw, transforms are stream based so inherently async, but of course they run in sequence on a given file. Maybe it has something to do with [this](https://github.com/benbria/aliasify/blob/bbeb4f2ff7872309a97c7588657d50bae6b035b3/src/aliasify.coffee#L35): [`options.jsFilesOnly`](https://github.com/benbria/browserify-transform-tools/blob/master/README.md#creating-a-string-transform). Anyway, I'm closing this issue because no one has provided a repro. I suspect your problem has to do with how those two transforms interact rather than something fundamental about how Browserify transforms work. Stackoverflow is one place you can try for help. If you're able to isolate a bug in Browserify's transform handling, please open a new issue with a minimal repro. If you need help getting started see [miniminirepro/browserify](https://github.com/miniminirepro/browserify/tree/api). Thanks!

**Closed by jmm** 2016-04-28 21:35 UTC
Labels: repro-please

**Comment by jmm** [comment] 2016-04-28 21:45
@kentmw Take a look at the [`appliesTo` option](https://github.com/benbria/aliasify#configuration) -- maybe it'll help you. Not sure how that interacts with the other option of the underlying lib, `jsFilesOnly`. If it doesn't work out, you could try my pathmodify plugin.

**Comment by kentmw** [comment] 2016-04-28 21:48
I modified `jsFilesOnly` in my downloaded node_modules/aliasify/aliasify.js, and it worked. At least, it worked in my case. I'll try out the `appliedTo` option, and move this conversation over to the aliasify project. Thank you so much for your help!
